version: '3.3'

networks:
  wordpress-network:
    driver: bridge

services: 
  db:
    image: srinikethvarma/postgres:latest
    restart: always
    ports:
      - '5432:5432'
    networks:
      - wordpress-network

  apache:
    image: srinikethvarma/wordpress:latest
    ports:
      - '80:80'
      - '443:443'
    networks:
      - wordpress-network
